# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 19:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2015, 11, 20, 19, 1, 32, 514352)),
        ),
    ]
