# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interest',
            table='interests',
        ),
    ]
